apiVersion: v1
kind: Pod
metadata:
  name: pod-with-host-port
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    ports: 
      - hostPort: 10000
        protocol: TCP
        containerPort: 80